version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/git_pull.sh
      runas: ShreyasChatApp

    - location: scripts/Env_requirements.sh
      runas: ShreyasChatApp

  ApplicationStart:
    - location: scripts/Restart_Migration.sh
      runas: ShreyasChatApp

