version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo ">>> Installing dependencies..."

      - source /home/ShreyasChatapp/venv/bin/activate
      - pip3 install -r requirements.txt

  pre_build:
    commands:
      - echo ">>> Running database migrations..."
      - bash ~/db_data.sh  # Ensure this script is available in your repo

  build:
    commands:
      - echo ">>> Running tests..."
      - python3 manage.py migrate

  post_build:
    commands:
      - echo ">>> Packaging the app for deployment..."
      - zip -r Django_Chatapp.zip . -x "venv/*" "*.git/*"

artifacts:
  files:
    - Django_Chatapp.zip
    - appspec.yml
    - scripts/*.sh
  discard-paths: no
