name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Backend Application
    runs-on: self-hosted

    env:
      WORKSPACE: ./ # Local project directory
      BACKEND_USER: ShreyasChatApp
      BACKEND_SERVER: 10.0.9.126
      CHATAPP_DIR: /Django_Chatapp
      SERVICE_NAME: django-backend
      SSH_KEY: /var/lib/jenkins/.ssh/id_rsa

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Sync files to the backend server
      - name: Sync files to the backend server
        run: |
          rsync -avz --exclude='.git/' \
            -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY" \
            $WORKSPACE/ $BACKEND_USER@$BACKEND_SERVER:$CHATAPP_DIR

          ssh -i "$SSH_KEY" $BACKEND_USER@$BACKEND_SERVER "ls -al $CHATAPP_DIR"

      # Step 3: Execute deployment tasks on the backend server
      - name: Deploy application
        run: |
          ssh -i "$SSH_KEY" $BACKEND_USER@$BACKEND_SERVER << 'EOF'
            set -e
            echo ">>> Activating virtual environment..."
            source ~/venv/bin/activate

            echo ">>> Navigating to project directory..."
            cd $CHATAPP_DIR

            echo ">>> Installing dependencies..."
            if [ -f requirements.txt ]; then
                pip3 install -r requirements.txt
            else
                echo "Error: requirements.txt not found!"
                exit 1
            fi

            echo ">>> Running database migrations..."
            bash ~/db_data.sh

            echo ">>> Restarting the service..."
            sudo systemctl restart $SERVICE_NAME

            echo ">>> Deployment complete!"
          EOF
