name: Deploy Django App on Host

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }}ubuntu@10.0.3.221 "echo SSH Connection Successful"

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@10.0.3.221 << 'EOF'
            cd ~/django_chatapp
            git pull origin main
          EOF
